/**
 * scripts/process_eruv_geojson.js
 *
 * Reads zurich_boundary.geojson (collection of LineString segments in [lng,lat] order),
 * groups them into separate closed rings (main boundary + inner river boundary etc.),
 * converts to {lat,lng} objects, and writes src/data/eruv_boundary.js.
 *
 * Run once:  node scripts/process_eruv_geojson.js
 */

const fs   = require('fs');
const path = require('path');

const INPUT  = path.join(__dirname, '..', 'zurich_boundary.geojson');
const OUTPUT = path.join(__dirname, '..', 'src', 'data', 'eruv_boundary.js');

const geojson  = JSON.parse(fs.readFileSync(INPUT, 'utf8'));
const segments = geojson.features
  .filter(f => f.geometry.type === 'LineString')
  .map(f => f.geometry.coordinates.map(c => ({ lng: c[0], lat: c[1] })));

console.log(`Loaded ${segments.length} LineString segments`);

const TOLERANCE = 0.0002; // ~15 m

function dist(a, b) {
  return Math.hypot(a.lat - b.lat, a.lng - b.lng);
}
function approxEq(a, b) { return dist(a, b) < TOLERANCE; }

/**
 * Build one closed ring by greedily chaining segments starting from `seed`.
 * Mutates `used` in-place. Returns the chain array.
 */
function buildRing(seed, used) {
  used[seed] = true;
  const chain = [...segments[seed]];

  let changed = true;
  while (changed) {
    changed = false;
    const tip = chain[chain.length - 1];
    for (let i = 0; i < segments.length; i++) {
      if (used[i]) continue;
      const seg = segments[i];
      if (approxEq(tip, seg[0])) {
        chain.push(...seg.slice(1));
        used[i] = true; changed = true; break;
      }
      if (approxEq(tip, seg[seg.length - 1])) {
        chain.push(...[...seg].reverse().slice(1));
        used[i] = true; changed = true; break;
      }
    }
  }

  // Close the ring
  if (!approxEq(chain[0], chain[chain.length - 1])) {
    chain.push({ ...chain[0] });
  }
  return chain;
}

// Extract all rings by repeatedly seeding from the next unused segment
const used  = new Array(segments.length).fill(false);
const rings  = [];

for (let i = 0; i < segments.length; i++) {
  if (!used[i]) {
    const ring = buildRing(i, used);
    rings.push(ring);
    console.log(`Ring ${rings.length}: ${ring.length} points, seed segment ${i}`);
  }
}

// Sort largest ring first (main boundary), then smaller ones (river etc.)
rings.sort((a, b) => b.length - a.length);

console.log(`\nTotal rings found: ${rings.length}`);
rings.forEach((r, i) => console.log(`  Ring ${i + 1}: ${r.length} points`));

// Write output — export as an array of rings
const js = `// Auto-generated by scripts/process_eruv_geojson.js — do not edit manually.
// ${rings.length} separate boundary ring(s) — render each as its own Polygon.
// Ring 0 = main eruv boundary (largest), Ring 1+ = inner/secondary boundaries (river, etc.)
const ERUV_RINGS = ${JSON.stringify(rings, null, 2)};

export default ERUV_RINGS;
`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT.replace('eruv_boundary', 'eruv_rings'), js, 'utf8');

// Also keep a flat merged export for backward compat with point-in-polygon checks
// (merge all ring coords for the containsLocation poly — the main ring is sufficient)
const flatJs = `// Auto-generated — the main eruv outer boundary for point-in-polygon checks.
const ERUV_BOUNDARY = ${JSON.stringify(rings[0], null, 2)};

export default ERUV_BOUNDARY;
`;
fs.writeFileSync(OUTPUT, flatJs, 'utf8');

// Export ALL raw segments as {lat,lng}[] arrays for polyline display.
// This preserves every sub-boundary (river, isolated stubs, etc.) exactly.
const rawSegments = segments; // already [{lat,lng}] from the map at top

const segJs = `// Auto-generated — all ${rawSegments.length} GeoJSON LineString segments as polylines.
// Render each as a separate Polyline to show every boundary including river stubs.
const ERUV_SEGMENTS = ${JSON.stringify(rawSegments, null, 2)};

export default ERUV_SEGMENTS;
`;
const segOutput = OUTPUT.replace('eruv_boundary', 'eruv_segments');
fs.writeFileSync(segOutput, segJs, 'utf8');

// Export all Polygon features (river boundaries, Tel HaMislaket, etc.)
// These have specific geometry arrays and styling.
const polygonFeatures = geojson.features.filter(f => f.geometry.type === 'Polygon');

// Convert Polygon [lng, lat] to {lat, lng} for Google Maps API
const parsedPolygons = polygonFeatures.map(f => {
  return {
    paths: f.geometry.coordinates.map(ring => ring.map(c => ({ lat: c[1], lng: c[0] }))),
    properties: f.properties || {}
  };
});

const polyJs = `// Auto-generated — ${parsedPolygons.length} GeoJSON Polygon features.
const ERUV_POLYGONS = ${JSON.stringify(parsedPolygons, null, 2)};

export default ERUV_POLYGONS;
`;
const polyOutput = OUTPUT.replace('eruv_boundary', 'eruv_polygons');
fs.writeFileSync(polyOutput, polyJs, 'utf8');

console.log(`\nWritten:\n  ${OUTPUT}\n  ${segOutput}\n  ${polyOutput}`);
