/**
 * scripts/process_eruv_geojson.js
 *
 * Reads zurich_boundary.geojson (collection of LineString segments in [lng,lat] order),
 * chains them into a single closed polygon, converts to {lat,lng} objects,
 * and writes src/data/eruv_boundary.js ready to import in React.
 *
 * Run once:  node scripts/process_eruv_geojson.js
 */

const fs   = require('fs');
const path = require('path');

const INPUT  = path.join(__dirname, '..', 'zurich_boundary.geojson');
const OUTPUT = path.join(__dirname, '..', 'src', 'data', 'eruv_boundary.js');

const geojson = JSON.parse(fs.readFileSync(INPUT, 'utf8'));

// Extract all LineString coordinate arrays [[lng,lat,?], ...]
const segments = geojson.features
  .filter(f => f.geometry.type === 'LineString')
  .map(f => f.geometry.coordinates.map(c => ({ lng: c[0], lat: c[1] })));

console.log(`Loaded ${segments.length} LineString segments`);

// Chain segments into a single ordered path.
// Uses a simple greedy algorithm: take the unvisited segment whose start OR end
// is closest to the current path tip (within tolerance), and append it.
const TOLERANCE = 0.0002; // ~15m in degrees

function dist(a, b) {
  return Math.hypot(a.lat - b.lat, a.lng - b.lng);
}

function approxEq(a, b) {
  return dist(a, b) < TOLERANCE;
}

const used = new Array(segments.length).fill(false);
const chain = [...segments[0]];
used[0] = true;

let changed = true;
while (changed) {
  changed = false;
  const tip = chain[chain.length - 1];
  for (let i = 0; i < segments.length; i++) {
    if (used[i]) continue;
    const seg = segments[i];
    if (approxEq(tip, seg[0])) {
      chain.push(...seg.slice(1));
      used[i] = true;
      changed = true;
      break;
    }
    if (approxEq(tip, seg[seg.length - 1])) {
      chain.push(...[...seg].reverse().slice(1));
      used[i] = true;
      changed = true;
      break;
    }
  }
}

const unused = used.filter(u => !u).length;
if (unused > 0) {
  console.warn(`⚠ ${unused} segments could not be chained — they will be added as disconnected sub-paths`);
  for (let i = 0; i < segments.length; i++) {
    if (!used[i]) {
      chain.push(...segments[i]);
    }
  }
}

console.log(`Chain built: ${chain.length} points`);

// Close the ring if needed
const first = chain[0], last = chain[chain.length - 1];
if (!approxEq(first, last)) {
  chain.push({ ...first });
  console.log('Ring closed (first ≠ last, appended first point)');
} else {
  console.log('Ring already closed ✓');
}

// Write output
const js = `// Auto-generated by scripts/process_eruv_geojson.js — do not edit manually.
// ${chain.length} coordinate points forming the Zurich Eruv boundary polygon.
const ERUV_BOUNDARY = ${JSON.stringify(chain, null, 2)};

export default ERUV_BOUNDARY;
`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, js, 'utf8');
console.log(`Written to ${OUTPUT}`);
